# Generated by Django 5.0.2 on 2024-04-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=120)),
                ('skill_icon', models.CharField(max_length=120)),
                ('create_att', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
